<?php

/**
 * Return all the languages' codes.
 */
function getLanguages() {
	return array_keys(LANGS);
}

/**
 * Returns the sentence separator. The default is
 * a single space between phrases.
 */
function getSeparator( $lang ) {
	if ( $lang === 'jbo' ) // Lojban
		return ' .i ';
	if (
			$lang === 'jpn' or // Japanese
			$lang === 'cmn' or // Chinese
			$lang === 'wuu' or // Shangainese
			$lang === 'lzh' // Literary Chinese
		)
		return '';
	else
		return ' ';
}

/**
 * Returns the direction of the language: left-to-right ('ltr')
 * or right-to-left ('rtl').
 */
function getDirection( $lang ) {
	if (
			$lang === 'ara' or // Arabic
			$lang === 'pes' or // Persian
			$lang === 'heb' or // Hebrew
			$lang === 'uig' or // Uygur
			$lang === 'arz' or // Egyptian Arabic
			$lang === 'yid' or // Yiddish
			$lang === 'acm' or // Iraq Arabic
			$lang === 'urd' )  // Urdu
		return 'rtl';
	else
		return 'ltr';
}

/**
 * Returns the English name of the language.
 */
function getEnglishName( $lang ) {
	if ( isset(LANGS[$lang]) )
		return LANGS[$lang];
	else
		return 'Unknown';
}

const LANGS = array(
	'abk' => 'Abkhaz',
	'ady' => 'Adyghe',
	'afh' => 'Afrihili',
	'afr' => 'Afrikaans',
	'ain' => 'Ainu',
	'akl' => 'Aklanon',
	'sqi' => 'Albanian',
	'arq' => 'Algerian Arabic',
	'amh' => 'Amharic',
	'grc' => 'Ancient Greek',
	'ara' => 'Arabic',
	'arg' => 'Aragonese',
	'hye' => 'Armenian',
	'asm' => 'Assamese',
	'aii' => 'Assyrian Neo-Aramaic',
	'ast' => 'Asturian',
	'awa' => 'Awadhi',
	'aym' => 'Aymara',
	'aze' => 'Azerbaijani',
	'ban' => 'Balinese',
	'bam' => 'Bambara',
	'bjn' => 'Banjar',
	'bak' => 'Bashkir',
	'eus' => 'Basque',
	'bar' => 'Bavarian',
	'bvy' => 'Baybayanon',
	'bel' => 'Belarusian',
	'ben' => 'Bengali',
	'ber' => 'Berber',
	'bho' => 'Bhojpuri',
	'brx' => 'Bodo',
	'bos' => 'Bosnian',
	'bre' => 'Breton',
	'bul' => 'Bulgarian',
	'mya' => 'Burmese',
	'bua' => 'Buryat',
	'yue' => 'Cantonese',
	'cat' => 'Catalan',
	'cay' => 'Cayuga',
	'ceb' => 'Cebuano',
	'bcl' => 'Central Bikol',
	'dtp' => 'Central Dusun',
	'nch' => 'Central Huasteca Nahuatl',
	'cmo' => 'Central Mnong',
	'cha' => 'Chamorro',
	'cbk' => 'Chavacano',
	'che' => 'Chechen',
	'chr' => 'Cherokee',
	'cjy' => 'Chinese (Jin)',
	'nya' => 'Chinyanja',
	'cho' => 'Choctaw',
	'ckt' => 'Chukchi',
	'chv' => 'Chuvash',
	'kzj' => 'Coastal Kadazan',
	'cor' => 'Cornish',
	'cos' => 'Corsican',
	'crh' => 'Crimean Tatar',
	'hrv' => 'Croatian',
	'cyo' => 'Cuyonon',
	'cycl' => 'CycL',
	'ces' => 'Czech',
	'dan' => 'Danish',
	'dng' => 'Dungan',
	'nld' => 'Dutch',
	'dws' => 'Dutton World Speedwords',
	'arz' => 'Egyptian Arabic',
	'egl' => 'Emilian',
	'eng' => 'English',
	'myv' => 'Erzya',
	'epo' => 'Esperanto',
	'est' => 'Estonian',
	'ewe' => 'Ewe',
	'ext' => 'Extremaduran',
	'fao' => 'Faroese',
	'hif' => 'Fiji Hindi',
	'fij' => 'Fijian',
	'fin' => 'Finnish',
	'fra' => 'French',
	'fry' => 'Frisian',
	'fur' => 'Friulian',
	'gag' => 'Gagauz',
	'glg' => 'Galician',
	'gan' => 'Gan Chinese',
	'gbm' => 'Garhwali',
	'kat' => 'Georgian',
	'deu' => 'German',
	'aln' => 'Gheg Albanian',
	'gil' => 'Gilbertese',
	'got' => 'Gothic',
	'ell' => 'Greek',
	'kal' => 'Greenlandic',
	'gos' => 'Gronings',
	'gcf' => 'Guadeloupean Creole French',
	'grn' => 'Guarani',
	'ngu' => 'Guerrero Nahuatl',
	'guj' => 'Gujarati',
	'afb' => 'Gulf Arabic',
	'hat' => 'Haitian Creole',
	'hak' => 'Hakka Chinese',
	'hau' => 'Hausa',
	'haw' => 'Hawaiian',
	'heb' => 'Hebrew',
	'hil' => 'Hiligaynon',
	'mrj' => 'Hill Mari',
	'hin' => 'Hindi',
	'mww' => 'Hmong Daw (White)',
	'hnj' => 'Hmong Njua (Green)',
	'hoc' => 'Ho',
	'hun' => 'Hungarian',
	'hrx' => 'Hunsrik',
	'iba' => 'Iban',
	'isl' => 'Icelandic',
	'ido' => 'Ido',
	'ibo' => 'Igbo',
	'ilo' => 'Ilocano',
	'ind' => 'Indonesian',
	'izh' => 'Ingrian',
	'ina' => 'Interlingua',
	'ile' => 'Interlingue',
	'acm' => 'Iraqi Arabic',
	'gle' => 'Irish',
	'ita' => 'Italian',
	'jam' => 'Jamaican Patois',
	'jpn' => 'Japanese',
	'jav' => 'Javanese',
	'jdt' => 'Juhuri (Judeo-Tat)',
	'quc' => 'K\'iche\'',
	'kab' => 'Kabyle',
	'xal' => 'Kalmyk',
	'kam' => 'Kamba',
	'kan' => 'Kannada',
	'pam' => 'Kapampangan',
	'krc' => 'Karachay-Balkar',
	'kaa' => 'Karakalpak',
	'krl' => 'Karelian',
	'kas' => 'Kashmiri',
	'csb' => 'Kashubian',
	'kaz' => 'Kazakh',
	'kek' => 'Kekchi (Q\'eqchi\')',
	'kxi' => 'Keningau Murut',
	'kjh' => 'Khakas',
	'kha' => 'Khasi',
	'khm' => 'Khmer',
	'kin' => 'Kinyarwanda',
	'run' => 'Kirundi',
	'tlh' => 'Klingon',
	'ksh' => 'Kölsch',
	'kor' => 'Korean',
	'avk' => 'Kotava',
	'kum' => 'Kumyk',
	'kur' => 'Kurdish',
	'fkv' => 'Kven Finnish',
	'kir' => 'Kyrgyz',
	'ldn' => 'Láadan',
	'lld' => 'Ladin',
	'lad' => 'Ladino',
	'lkt' => 'Lakota',
	'lao' => 'Lao',
	'lat' => 'Latin',
	'lvs' => 'Latvian',
	'lzz' => 'Laz',
	'lij' => 'Ligurian',
	'lin' => 'Lingala',
	'lfn' => 'Lingua Franca Nova',
	'lzh' => 'Literary Chinese',
	'lit' => 'Lithuanian',
	'liv' => 'Livonian',
	'jbo' => 'Lojban',
	'lmo' => 'Lombard',
	'lou' => 'Louisiana Creole',
	'nds' => 'Low German (Low Saxon)',
	'dsb' => 'Lower Sorbian',
	'lug' => 'Luganda',
	'ltz' => 'Luxembourgish',
	'mkd' => 'Macedonian',
	'mad' => 'Madurese',
	'mai' => 'Maithili',
	'mlg' => 'Malagasy',
	'zsm' => 'Malay',
	'zlm' => 'Malay (Vernacular)',
	'mal' => 'Malayalam',
	'mlt' => 'Maltese',
	'mgm' => 'Mambae',
	'mnc' => 'Manchu',
	'cmn' => 'Mandarin Chinese',
	'glv' => 'Manx',
	'mri' => 'Maori',
	'mar' => 'Marathi',
	'mah' => 'Marshallese',
	'mhr' => 'Meadow Mari',
	'mic' => 'Mi\'kmaq',
	'enm' => 'Middle English',
	'frm' => 'Middle French',
	'nan' => 'Min Nan Chinese',
	'min' => 'Minangkabau',
	'moh' => 'Mohawk',
	'mdf' => 'Moksha',
	'mnw' => 'Mon',
	'mon' => 'Mongolian',
	'mfe' => 'Morisyen',
	'ary' => 'Moroccan Arabic',
	'nst' => 'Naga (Tangshang)',
	'nah' => 'Nahuatl',
	'nau' => 'Nauruan',
	'nav' => 'Navajo',
	'npi' => 'Nepali',
	'ngt' => 'Ngeq ',
	'fuv' => 'Nigerian Fulfulde',
	'niu' => 'Niuean',
	'nog' => 'Nogai',
	'apc' => 'North Levantine Arabic',
	'max' => 'North Moluccan Malay',
	'sme' => 'Northern Sami',
	'nob' => 'Norwegian Bokmål',
	'nno' => 'Norwegian Nynorsk',
	'nov' => 'Novial',
	'oci' => 'Occitan',
	'ori' => 'Odia (Oriya)',
	'oji' => 'Ojibwe',
	'oar' => 'Old Aramaic',
	'orv' => 'Old East Slavic',
	'ang' => 'Old English',
	'non' => 'Old Norse',
	'prg' => 'Old Prussian',
	'osx' => 'Old Saxon',
	'tpw' => 'Old Tupi',
	'otk' => 'Old Turkish',
	'nlv' => 'Orizaba Nahuatl',
	'oss' => 'Ossetian',
	'ota' => 'Ottoman Turkish',
	'pfl' => 'Palatine German',
	'pau' => 'Palauan',
	'pag' => 'Pangasinan',
	'pap' => 'Papiamento',
	'pus' => 'Pashto',
	'pdc' => 'Pennsylvania German',
	'pes' => 'Persian',
	'pcd' => 'Picard',
	'pms' => 'Piedmontese',
	'ppl' => 'Pipil',
	'pol' => 'Polish',
	'por' => 'Portuguese',
	'fuc' => 'Pulaar',
	'pan' => 'Punjabi (Eastern)',
	'pnb' => 'Punjabi (Western)',
	'que' => 'Quechua',
	'qya' => 'Quenya',
	'rap' => 'Rapa Nui',
	'rom' => 'Romani',
	'ron' => 'Romanian',
	'roh' => 'Romansh',
	'rus' => 'Russian',
	'rue' => 'Rusyn',
	'smo' => 'Samoan',
	'sgs' => 'Samogitian',
	'sag' => 'Sango',
	'san' => 'Sanskrit',
	'srd' => 'Sardinian',
	'sco' => 'Scots',
	'gla' => 'Scottish Gaelic',
	'srp' => 'Serbian',
	'tsn' => 'Setswana',
	'crs' => 'Seychellois Creole',
	'wuu' => 'Shanghainese',
	'sna' => 'Shona',
	'shs' => 'Shuswap',
	'scn' => 'Sicilian',
	'sjn' => 'Sindarin',
	'snd' => 'Sindhi',
	'sin' => 'Sinhala',
	'slk' => 'Slovak',
	'slv' => 'Slovenian',
	'som' => 'Somali',
	'alt' => 'Southern Altai',
	'sma' => 'Southern Sami',
	'sot' => 'Southern Sotho',
	'spa' => 'Spanish',
	'sux' => 'Sumerian',
	'sun' => 'Sundanese',
	'swg' => 'Swabian',
	'swh' => 'Swahili',
	'ssw' => 'Swazi',
	'swe' => 'Swedish',
	'gsw' => 'Swiss German',
	'shy' => 'Tachawit',
	'mvv' => 'Tagal Murut',
	'tgl' => 'Tagalog',
	'thv' => 'Tahaggart Tamahaq',
	'tah' => 'Tahitian',
	'tgk' => 'Tajik',
	'tzl' => 'Talossan',
	'tly' => 'Talysh',
	'tam' => 'Tamil',
	'rif' => 'Tarifit',
	'tat' => 'Tatar',
	'tel' => 'Telugu',
	'tmw' => 'Temuan',
	'tet' => 'Tetun',
	'tha' => 'Thai',
	'bod' => 'Tibetan',
	'tig' => 'Tigre',
	'tir' => 'Tigrinya',
	'tpi' => 'Tok Pisin',
	'tkl' => 'Tokelauan',
	'toki' => 'Toki Pona',
	'ton' => 'Tongan',
	'tso' => 'Tsonga',
	'tur' => 'Turkish',
	'tuk' => 'Turkmen',
	'tvl' => 'Tuvaluan',
	'tyv' => 'Tuvinian',
	'aoz' => 'Uab Meto',
	'udm' => 'Udmurt',
	'ukr' => 'Ukrainian',
	'umb' => 'Umbundu',
	'unknown' => 'Unknown',
	'hsb' => 'Upper Sorbian',
	'urd' => 'Urdu',
	'urh' => 'Urhobo',
	'uig' => 'Uyghur',
	'uzb' => 'Uzbek',
	'vec' => 'Venetian',
	'vep' => 'Veps',
	'vie' => 'Vietnamese',
	'vol' => 'Volapük',
	'vro' => 'Võro',
	'wln' => 'Walloon',
	'war' => 'Waray',
	'cym' => 'Welsh',
	'wol' => 'Wolof',
	'xho' => 'Xhosa',
	'hsn' => 'Xiang Chinese',
	'sah' => 'Yakut',
	'yid' => 'Yiddish',
	'yor' => 'Yoruba',
	'zza' => 'Zaza',
	'zul' => 'Zulu'
);

?>
